### ISSUE TITLE
Using TheLastBen's SD Colab I get this..

### ISSUE THREAD

**Issue by HorrySheet** [LonicaMewinsky/gif2gif#17]
A bunch of windows show up ERROR after uploading a gif I downloaded from gify and another website. Simple animated gif 230x230ish in resolution.  Installed the extension via the extensions list in Automatic1111's GUI and restarted the UI and even re-ran all the cells in the colab. Still getting this.. What could be wrong? 

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/gif2gif/scripts/gif2gif.py", line 176, in processgif
    converted = frame.resize((round(480*frame.width/frame.height), 480), Image.Resampling.LANCZOS).convert('RGBA')
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'

**Comment by LonicaMewinsky** [comment]
I do not use this collab myself, but I have some suspicions. I recently updated this script to no longer use temporary files, which collabs I think would have problems with. Mind updating and trying again?
