### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by boundlessliving** [LonicaMewinsky/gif2gif#28]
This was working well for me, but yestereday all attempts fail. As soon as I start the process I get the error thatIndexError: list index out of range

Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\sd\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\sd\stable-diffusion-webui\modules\img2img.py", line 180, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\sd\stable-diffusion-webui\modules\scripts.py", line 408, in run
    processed = script.run(p, *script_args)
  File "D:\sd\stable-diffusion-webui\extensions\gif2gif\scripts\gif2gif.py", line 314, in run
    gif_filename = (modules.images.save_image(inc_frames[0], outpath, "gif2gif", extension = 'gif')[0])
IndexError: list index out of range

I've done all kinds of looking into this, but my code knowledge is basically non-existent, so I'm not sure what's happening.

**Comment by tmasakas** [comment]
Removing the "gif2gif" folder from "extension" and reinstalling it fixed the issue for me
